### PR TITLE
Duplicate keys detection using Feature.STRICT_DUPLICATE_DETECTION.

### PR DESCRIPTION
**Pull request by wilx**

### CODE REVIEW

**Comment by wilx** [comment]
This closes #2.

**Comment by sylvainlaurent** [comment]
thanks for your PR, this is interesting. I actually wonder if this should not be enabled by default actually. People using this plugin aim at having proper json/yaml files and duplicate keys are not really clean in such files.
What do you think?
Furthermore, the flag should be "documented" in the `/README.md` file.

**Comment by wilx** [comment]
I have committed change to turn it on by default. I started with off by default to keep the status quo. But I agree that duplicate keys are not clean.

**Comment by sylvainlaurent** [comment]
thanks for your PR!

**Pull request merged**
